examenParcial/examenParcial/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestionTienda.urls')),
    path('', RedirectView.as_view(url='gestionTienda/', permanent=True)),
]

examenParcial/gestionTienda/urls.py
from django.urls import path
from . import views

app_name = 'gestionTienda'

urlpatterns = [
    path('gestionTienda/', views.tiendas, name='tiendas'),
    path('gestionTienda/lista', views.listaTienda, name='listaTienda'),
    path('gestionTienda/agregar', views.agregarTienda, name='agregarTienda'),
    path('gestionTienda/<int:pk>/editar', views.editarTienda, name='editarTienda'),
    path('gestionTienda/<int:pk>/eliminar', views.eliminarTienda, name='eliminarTienda'),
    path('gestionTienda/limpiar', views.eliminarTiendas, name='eliminarTiendas'),
    path('gestionTienda/<int:pk>/detalles/', views.detalleTienda, name='detalleTienda'),
    path('gestionTienda/<int:pk>/detalles/lista', views.listaTiendaFiltro, name='listaTiendaFiltro'),
    path('gestionTienda/Productos/', views.productos, name='productos'),
    path('gestionTienda/Productos/lista', views.listaProducto, name='listaProducto'),
    path('gestionTienda/Productos/agregar', views.agregarProducto, name='agregarProducto'),
    path('gestionTienda/Productos/<int:pk>/editar', views.editarProducto, name='editarProducto'),
    path('gestionTienda/Productos/<int:pk>/eliminar', views.eliminarProducto, name='eliminarProducto'),
    path('gestionTienda/Productos/limpiar', views.eliminarProductos, name='eliminarProductos'),
]

examenParcial/gestionTienda/models.py
from django.db import models

class Tienda(models.Model):
  direccion = models.CharField(max_length=32, blank=True, null=True, unique=True)
  provincia = models.CharField(max_length=32, blank=True, null=True)
  region = models.CharField(max_length=32, blank=True, null=True)
  fechaCreacion = models.CharField(max_length=32, blank=True, null=True)
  telefono = models.CharField(max_length=32, blank=True, null=True, unique=True)

  def __str__(self):
    return self.direccion

class Producto(models.Model):
  descripcion = models.CharField(max_length=32, blank=True, null=True)
  codigo = models.CharField(max_length=32, blank=True, null=True, unique=True)
  precioVenta = models.CharField(max_length=32, blank=True, null=True)
  cantidad = models.CharField(max_length=32, blank=True, null=True)
  tiendaRelacionada = models.ForeignKey(Tienda,on_delete=models.SET_NULL,blank=True, null=True)

examenParcial/gestionTienda/forms.py
from django import forms
from .models import Tienda, Producto

class TiendaForm(forms.ModelForm):
    class Meta:
        model = Tienda
        fields = ['direccion', 'provincia', 'region', 'fechaCreacion', 'telefono']

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['descripcion', 'codigo', 'precioVenta', 'cantidad', 'tiendaRelacionada']

examenParcial/gestionTienda/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.http import require_POST
import json

from .models import Tienda, Producto
from .forms import TiendaForm, ProductoForm

# views tienda.
def tiendas(request):
    return render(request, 'tiendas.html')

def listaTienda(request):
    tiendas = Tienda.objects.all()
    return render(request, "listaTienda.html", {
        'tiendas': tiendas
    })

def listaTiendaFiltro(request, pk):
    tienda = get_object_or_404(Tienda, pk=pk)
    try:
        productos = Producto.objects.filter(tiendaRelacionada=tienda)
    except:
        productos = None
    return render(request, "listaProducto.html", {
        'productos': productos
    })

def agregarTienda(request):
    if request.method == 'POST':
        form = TiendaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        'listaTiendaCambio': None,
                    })
                }
            )
    else:
        form = TiendaForm()
    return render(request, 'tiendaForm.html', {'form':form})

def editarTienda(request, pk):
    tienda = get_object_or_404(Tienda, pk=pk)
    if request.method == "POST":
        form = TiendaForm(request.POST, instance=tienda)
        if form.is_valid():
            form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        'listaTiendaCambio': None,
                    })
                }
            )
    else:
        form = TiendaForm(instance=tienda)
    return render(request, 'tiendaForm.html', {
        'form': form,
        'tienda': tienda,
    })

def eliminarTiendas(request):
    print(request)
    if request.method == 'POST':
        Tienda.objects.all().delete()
        return HttpResponse(
            status=204,
            headers={
                'HX-Trigger': json.dumps({
                    'listaTiendaCambio': None,
                })
            }
        )
    return render(request, 'borrarTiendaForm.html')

def detalleTienda(request, pk):
    tienda = get_object_or_404(Tienda, pk=pk)
    return render(request, 'detalleTienda.html', {
        'tienda':tienda,
    })

@ require_POST
def eliminarTienda(request, pk):
    tienda = get_object_or_404(Tienda, pk=pk)
    tienda.delete()
    return HttpResponse(
        status=204,
        headers={
            'HX-Trigger': json.dumps({
                'listaTiendaCambio': None,
            })
        })

# views producto.
def productos(request):
    return render(request, 'productos.html')

def listaProducto(request):
    productos = Producto.objects.all()
    return render(request, "listaProducto.html", {
        'productos': productos
    })

def agregarProducto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        'listaProductoCambio': None,
                    })
                }
            )
    else:
        form = ProductoForm()
    return render(request, 'productoForm.html', {'form':form})

def editarProducto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if request.method == "POST":
        form = ProductoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
            return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        'listaProductoCambio': None,
                    })
                }
            )
    else:
        form = ProductoForm(instance=producto)
    return render(request, 'productoForm.html', {
        'form': form,
        'producto': producto,
    })

def eliminarProductos(request):
    print(request)
    if request.method == 'POST':
        Producto.objects.all().delete()
        return HttpResponse(
            status=204,
            headers={
                'HX-Trigger': json.dumps({
                    'listaProductoCambio': None,
                })
            }
        )
    return render(request, 'borrarProductoForm.html')

@ require_POST
def eliminarProducto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    producto.delete()
    return HttpResponse(
        status=204,
        headers={
            'HX-Trigger': json.dumps({
                'listaProductoCambio': None,
            })
        })

examenParcial/gestionTienda/templates/borrarProductoForm.html
<form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content p-3">
  <div class="modal-header">
    <h5 class="modal-title">Desea eliminar todos los datos?</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-danger" hx-post="{% url 'gestionTienda:eliminarProductos'%}">
      Borrar
    </button>
    <span class="flex-grow-1"></span>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
      Cerrar
    </button>
  </div>
</form>

examenParcial/gestionTienda/templates/borrarTiendaForm.html
<form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content p-3">
  <div class="modal-header">
    <h5 class="modal-title">Desea eliminar todos los datos?</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-danger" hx-post="{% url 'gestionTienda:eliminarTiendas'%}">
      Borrar
    </button>
    <span class="flex-grow-1"></span>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
      Cerrar
    </button>
  </div>
</form>

examenParcial/gestionTienda/templates/detalleTienda.html
{% extends "master.html" %}
{% load static %}

{% block title %}
  Tienda {{ tienda.direccion }}
{% endblock %}

{% block header %}
  Tienda {{ tienda.direccion }}
{% endblock %}

{% block buttons %}
  <div class="col-2">
    <button hx-get="{% url 'gestionTienda:agregarProducto' %}" hx-target="#editar" class="btn btn-success w-100" >Crear <i class="fa-solid fa-plus"></i></button>
  </div>
  <div class="col-2">
    <button hx-get="{% url 'gestionTienda:eliminarProductos' %}" hx-target="#borrar" class="btn btn-danger w-100">Eliminar Todo <i class="fa-solid fa-trash"></i></button>
  </div>
{% endblock %}

{% block content %}
  <div class="col-10">
    <table class="table">
      <thead class="table-dark">
        <th>ID</th>
        <th>Descripcion</th>
        <th>Codigo</th>
        <th>Precio de Venta</th>
        <th>Cantidad</th>
        <th>Tienda</th>
        <th>Editar</th>
      </thead>
      <tbody hx-trigger="load, listaProductoCambio from:body" hx-get="{% url 'gestionTienda:listaTiendaFiltro' pk=tienda.pk  %}" hx-target="this"> 
      </tbody>
    </table>
  </div>
{% endblock %}

{% block modal %}
  <div id="modal" class="modal fade">
    <div id="editar" class="modal-dialog" hx-target="this"></div>
  </div>

  <div id="modalDelete" class="modal fade">
    <div id="borrar" class="modal-dialog" hx-target="this"></div>
  </div>

  <script src="https://unpkg.com/htmx.org@1.6.1/dist/htmx.min.js"></script>
  <script src="{% static 'modalEdit.js' %}"></script>
{% endblock %}

examenParcial/gestionTienda/templates/listaProducto.html
{% for producto in productos %}
<tr id="producto-{{ producto.pk }}">
  <td>{{ producto.id }}</td>
  <td>{{ producto.descripcion }}</td>
  <td>{{ producto.codigo }}</td>
  <td>{{ producto.precioVenta }}</td>
  <td>{{ producto.cantidad }}</td>
  <td>{{ producto.tiendaRelacionada }}</td>
  <td>
    <button class="btn btn-primary btn-sm" hx-get="{% url 'gestionTienda:editarProducto' pk=producto.pk %}" hx-target="#editar">
      <i class="fa-solid fa-pen-to-square"></i>
    </button>
  </td>
</tr>
{% endfor %}

examenParcial/gestionTienda/templates/listaTienda.html
{% for tienda in tiendas %}
<tr id="tienda-{{ tienda.pk }}">
  <td>{{ tienda.id }}</td>
  <td>{{ tienda.direccion }}</td>
  <td>{{ tienda.provincia }}</td>
  <td>{{ tienda.region }}</td>
  <td>{{ tienda.fechaCreacion }}</td>
  <td>{{ tienda.telefono }}</td>
  <td class="justify-content-center">
    <button class="btn btn-primary btn-sm" hx-get="{% url 'gestionTienda:editarTienda' pk=tienda.pk %}" hx-target="#editar">
      <i class="fa-solid fa-pen-to-square"></i>
    </button>
  </td>
  <td>
    <a href="{% url 'gestionTienda:detalleTienda' pk=tienda.pk %}">
      <button class="btn btn-primary btn-sm">
        <i class="fa-solid fa-circle-info"></i>
      </button>
    </a>
  </td>
</tr>
{% endfor %}

examenParcial/gestionTienda/templates/master.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar navbar-dark justify-content-between px-3 py-3" style="background-color: #24252a;">
      <div class="container pl-0">
        <i class="fa-brands fa-shopify fa-2xl mx-1" style="color: #ffffff;"></i>
        <div class="collapse navbar-collapse">
          <div class="navbar-nav">
            <a class="nav-item nav-link active mx-2" href="{% url 'gestionTienda:tiendas' %}">Tiendas <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link active mx-2" href="{% url 'gestionTienda:productos' %}">Productos</a>
          </div>
        </div>
      </div>
    </nav>
    <div class="p-3">
      <div class="container mt-5">
        <h1>
          {% block header %}
          {% endblock %}
        </h1>
      </div>
      <div class="container mt-5">
        <div class="row">
          {% block buttons %}
          {% endblock %}
        </div>
      </div>
      <div class="container mt-5">
        <div class="row justify-content-center">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
    {% block modal %}
    {% endblock %}
  </body>
</html>

examenParcial/gestionTienda/templates/productoForm.html
{% load widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
  <form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content p-3">
    <div class="modal-header">
      {% if producto %}
        <h5 class="modal-title">Editar Producto</h5>
      {% else %}
        <h5 class="modal-title">Crear Producto</h5>
      {% endif %}
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}" class="form-label m-2">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
          <div class="invalid-feedback d-block">{{ error }}</div>
        {% endfor %}
      </div>
    {% endfor %}
    <div class="modal-footer">
      {% if producto %}
      <button type="button" class="btn btn-danger" hx-post="{% url 'gestionTienda:eliminarProducto' pk=producto.pk %}">
        Remove
      </button>
      <span class="flex-grow-1"></span>
      {% endif %}
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
        Cancel
      </button>
      <button type="submit" class="btn btn-primary">
        Save
      </button>
    </div>
  </form>
{% endwith %}

examenParcial/gestionTienda/templates/productos.html
{% extends "master.html" %}

{% block title %}
  Productos
{% endblock %}

{% block header %}
  Productos
{% endblock %}

{% block buttons %}
  <div class="col-2">
    <button class="btn btn-success w-100" data-bs-toggle="modal" data-bs-target="#crear">Crear <i class="fa-solid fa-plus"></i></button>
  </div>
  <div class="col-2">
    <button class="btn btn-success w-100" data-bs-toggle="modal" data-bs-target="#agregar">Agregar a Tienda <i class="fa-solid fa-paperclip"></i></button>
  </div>
  <div class="col-2">
    <button class="btn btn-danger w-100" data-bs-toggle="modal" data-bs-target="#eliminar">Eliminar Todo <i class="fa-solid fa-trash"></i></button>
  </div>
{% endblock %}

{% block content %}

{% endblock %}

examenParcial/gestionTienda/templates/tiendaForm.html
{% load widget_tweaks %}
{% with WIDGET_ERROR_CLASS='is-invalid' %}
  <form hx-post="{{ request.path }}" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' class="modal-content p-3">
    <div class="modal-header">
      {% if edit %}
        <h5 class="modal-title">Editar Tienda</h5>
      {% else %}
        <h5 class="modal-title">Crear Tienda</h5>
      {% endif %}
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    {% for field in form.visible_fields %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}" class="form-label m-2">{{ field.label }}</label>
        {{ field|add_class:'form-control' }}
        {% for error in field.errors %}
          <div class="invalid-feedback d-block">{{ error }}</div>
        {% endfor %}
      </div>
    {% endfor %}
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
        Cancel
      </button>
      <button type="submit" class="btn btn-primary">Save</button>
    </div>
  </form>
{% endwith %}

examenParcial/gestionTienda/templates/tiendas.html
{% extends "master.html" %}
{% load static %}

{% block title %}
  Tiendas
{% endblock %}

{% block header %}
  Tiendas
{% endblock %}

{% block buttons %}
  <div class="col-2">
    <button hx-get="{% url 'gestionTienda:agregarTienda' %}" hx-target="#editar" class="btn btn-success w-100" >Crear <i class="fa-solid fa-plus"></i></button>
  </div>
  <div class="col-2">
    <button hx-get="{% url 'gestionTienda:eliminarTiendas' %}" hx-target="#borrar" class="btn btn-danger w-100">Eliminar Todo <i class="fa-solid fa-trash"></i></button>
  </div>
{% endblock %}

{% block content %}
  <div class="col-10">
    <table class="table">
      <thead class="table-dark">
        <th>ID</th>
        <th>Direccion</th>
        <th>Provincia</th>
        <th>Region</th>
        <th>Fecha de creacion</th>
        <th>Telefono</th>
        <th>Editar</th>
        <th>Detalles</th>
      </thead>
      <tbody hx-trigger="load, listaTiendaCambio from:body" hx-get="{% url 'gestionTienda:listaTienda' %}" hx-target="this"> 
      </tbody>
    </table>
  </div>
{% endblock %}

{% block modal %}
  <div id="modal" class="modal fade">
    <div id="editar" class="modal-dialog" hx-target="this"></div>
  </div>

  <div id="modalDelete" class="modal fade">
    <div id="borrar" class="modal-dialog" hx-target="this"></div>
  </div>

  <script src="https://unpkg.com/htmx.org@1.6.1/dist/htmx.min.js"></script>
  <script src="{% static 'modalEdit.js' %}"></script>
{% endblock %}